### ISSUE TITLE
Compilation terminated - whom to ask for help? 

### ISSUE THREAD

**Issue by altacoon** [idstein/esphome-optolink#2]
Hi everybody,
I want to read data from my 20 year old Viessmann Vitotronic200 KW2. I found this github-source: "github.com/openv/openv/wiki/esphome-optolink", edited by @j0ta29

The  yaml-file I have created is based on the example, given on the same website. But it is not compiled correctly, compilation is terminated. 
I created an issue on the openv-issue-tracker, (#591) but it was closed and I was asked to open an issue on this tracker. 

This is the yaml-file:
```
  name: viessmann-optolink
  friendly_name: viessmann-optolink

esp8266:
  board: d1_mini

# Enable logging
logger:
  hardware_uart: UART1 
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxx"

ota:
  password: "xxxxxxxxxx"

wifi:
  ssid: !secret wifi_1_ssid
  password: !secret wifi_1_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Viessmann-Optolink"
    password: "xxxxxxxxxxxxxxx"

external_components:
  - source: github://pr#4453
    components: [ optolink ]

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  #rx_buffer_size: 2048
  data_bits: 8
  stop_bits: 2             #Quelle für die Daten der seriellen Schnittstelle "KW":https://github.com/openv/openv/wiki/Protokoll-KW
  parity: Even

optolink:
  protocol: KW             # P300 oder KW
  logger: enable             # wenn später alles rund läuft, wieder entfernen 
  state: Status              # wenn später alles rund läuft, wieder entfernen
  device_info: Vitotronic200KW2 # dient zur Identifizierung der Vitotronic

sensor:
  - platform: optolink
    name: Aussentemperatur
    address: 0x0800
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
  - platform: optolink  
    name: Brennerstarts
    address: 0x088A
    bytes: 4
    div_ratio: 1
  - platform: optolink
    name: Oelverbrauch
    address: 0x7574
    bytes: 4
    div_ratio: 1
    unit_of_measurement: L
    device_class: volume
  - platform: optolink
    name: Betriebsstunden
    address: 0x08A7
    bytes: 4
    unit_of_measurement: s
    device_class: duration
    ```

And this is the log of the compilation:

INFO Reading configuration /config/esphome/viessmann-optolink.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing viessmann-optolink (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
| |-- ESPAsyncTCP-esphome @ 1.2.3
| |-- Hash @ 1.0
| |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
| |-- libsodium @ 1.10018.1
|-- VitoWiFi @ 1.0.2
Compiling /data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_device_info_sensor.cpp.o
Compiling /data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_number.cpp.o
Compiling /data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_select.cpp.o
Compiling /data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_sensor_base.cpp.o
In file included from src/esphome/components/optolink/optolink_sensor_base.cpp:3:
src/esphome/components/optolink/optolink_sensor_base.h:6:10: fatal error: esphome/core/string_ref.h: No such file or directory
6 | #include "esphome/core/string_ref.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_sensor_base.cpp.o] Error 1
In file included from src/esphome/components/optolink/optolink_number.h:6,
from src/esphome/components/optolink/optolink_number.cpp:3:
src/esphome/components/optolink/optolink_sensor_base.h:6:10: fatal error: esphome/core/string_ref.h: No such file or directory
6 | #include "esphome/core/string_ref.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_number.cpp.o] Error 1
In file included from src/esphome/components/optolink/optolink_device_info_sensor.h:7,
from src/esphome/components/optolink/optolink_device_info_sensor.cpp:4:
src/esphome/components/optolink/optolink_sensor_base.h:6:10: fatal error: esphome/core/string_ref.h: No such file or directory
6 | #include "esphome/core/string_ref.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_device_info_sensor.cpp.o] Error 1
In file included from src/esphome/components/optolink/optolink_select.h:8,
from src/esphome/components/optolink/optolink_select.cpp:3:
src/esphome/components/optolink/optolink_sensor_base.h:6:10: fatal error: esphome/core/string_ref.h: No such file or directory
6 | #include "esphome/core/string_ref.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/viessmann-optolink/.pioenvs/viessmann-optolink/src/esphome/components/optolink/optolink_select.cpp.o] Error 1
========================== [FAILED] Took 4.20 seconds ==========================
